projects:
  stripe:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  example:
    schemaPath: example/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
