projects:
  stripe:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4001
  example:
    schemaPath: example/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4001
